---
- name: Configure APT Mirror and Send Notification
  hosts: all
  become: yes
  vars:
    mirror_url: "http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu"
    release: "noble"
    is_kali: "{{ ansible_distribution == 'Kali' }}"

    # Sources for Kali
    sources_content_kali: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }} main restricted universe multiverse
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }}-updates main restricted universe multiverse
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }}-security main restricted universe multiverse

    # Sources for Mint/Ubuntu
    sources_content_mint: |
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }} main restricted universe multiverse
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-updates main restricted universe multiverse
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-security main restricted universe multiverse

    # Multiple recipients (comma-separated)
    notification_recipients: "aravind_slcs_intern2@aravind.org"

  tasks:
    - name: Patch and Notify Block
      block:
        - name: Update sources.list with local mirror
          copy:
            dest: /etc/apt/sources.list
            content: "{{ sources_content_kali if is_kali else sources_content_mint }}"
          register: sources_result

        - name: Update APT package cache
          apt:
            update_cache: yes
          register: apt_result

      rescue:
        - name: Set patch_status to failed
          set_fact:
            patch_status: "❌ FAILED"
        - name: Set fallback results
          set_fact:
            sources_result: { changed: false }
            apt_result: { changed: false }

      always:
        - name: Send notification email
          delegate_to: localhost
          become: false
          community.general.mail:
            host: smtp.gmail.com
            port: 587
            secure: starttls
            username: "{{ lookup('env', 'EMAIL_USER') }}"
            password: "{{ lookup('env', 'EMAIL_PASSWORD') }}"
            to: "{{ notification_recipients }}"
            from: "{{ lookup('env', 'EMAIL_USER') }}"
            subject: "{{ patch_status | default('✅ SUCCESS') }} Mirror Patch Report - {{ inventory_hostname }}"
            body: |
              Hello Team,

              The system **{{ inventory_hostname }}** has completed the mirror patch operation.

              🖥️ Hostname         : {{ inventory_hostname }}
              🧠 OS               : {{ ansible_distribution }} {{ ansible_distribution_version }}
              🌐 Mirror URL       : {{ mirror_url }}
              📦 Release          : {{ release }}
              📅 Timestamp        : {{ ansible_date_time.iso8601 }}

              📁 Source list file : {{ '✅ Updated' if sources_result.changed else '✅ Already Configured' }}
              🔄 APT Cache Status : {{ '✅ Refreshed' if apt_result.changed else '🔄 No Updates Needed' }}

              Regards,  
              🔧 Ansible Automation System
